name: Welcome New Contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "🎉 Thanks for opening your first pull request! We're excited to have you contribute to this project by Jaijit Singh. Please check out our contributing guidelines and enjoy your journey as a contributor!"
